language: node_js
node_js:
  - "15"

before_script:
  - npm install -g gulp-cli

# Travis will run `bundle install` by default before running our script
script:
  - gulp build

# See https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master

notifications:
  slack: $SLACK_NOTIFICATION_TOKEN
  email: false
