language: node_js
# only run CI-builds on master branch
branches:
  only:
    - master
node_js:
  - "10"
# set execution permission on our build script
before_script:
  - chmod +x ./script/cibuild
  - npm install -g gulp-cli
# path to our build script.
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false
notifications:
  slack: competemcgill:wNWajErpGDlte46AowkyxMxP
  email: false